
# Mount folders containing TLS cert and user secrets (For TLS certificate)
x-cert-volumes: &cert-volumes
  - ${APPDATA}\microsoft\UserSecrets:/root/.microsoft/usersecrets
  - ${USERPROFILE}\.aspnet\https:/root/.aspnet/https

# Kestrel uses this env variable to locate the TLS certificate
x-cert-path: &cert-path 
  Kestrel__Certificates__Default__Path: "/root/.aspnet/https/susine.dev.pfx"

services:    
  identity.susine.dev:  
    build:
      context: .
      dockerfile: ./Identity.Server/Dockerfile
      target: dev
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    networks:
      - backend
    ports:
      - 7082:7082
    develop:
      watch:
        - action: rebuild
          path: .
    image: local/identity-susine-dev
    
  matchmaking.susine.dev:
    build:
      context: .
      dockerfile: ./MatchMaking.Api/Dockerfile
      target: dev
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    networks:
      - backend
    ports:
      - 7148:7148
    develop:
      watch:
        - action: rebuild
          path: .
    image: local/matchmaking-susine-dev

  gso.susine.dev:
    build:
      context: .
      dockerfile: ./GameServerOrchestrator/Dockerfile
      target: dev
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    networks:
      - backend
    ports:
      - 7227:7227
    develop:
      watch:
        - action: rebuild
          path: .
    image: local/gso-susine-dev

networks:
  backend:
