apiVersion: v1
kind: ServiceAccount
metadata:
  name: service-account-gso
  namespace: susine-infra
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pod-creator
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: binding-pod-creator
subjects:
  - kind: ServiceAccount
    name: service-account-gso
    namespace: susine-infra
roleRef:
  kind: ClusterRole
  name: pod-creator
  apiGroup: rbac.authorization.k8s.io