apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: susine-infra
build:
  local:
    concurrency: 4
  tagPolicy:
    sha256: {}
  artifacts:
    - image: willypain.local:5000/identity-susine-dev
      context: .
      docker:
        dockerfile: Identity.Server/Dockerfile
        target: dev
    - image: willypain.local:5000/matchmaking-susine-dev
      context: .
      docker:
        dockerfile: MatchMaking.Api/Dockerfile
        target: dev
    - image: willypain.local:5000/gso-susine-dev
      context: .
      docker:
        dockerfile: GameServerOrchestrator/Dockerfile
        target: dev
manifests:
  rawYaml:
  #probs should move these into folders rather than grouping by file name  
    - '*.local.k8s.yaml'
    - 'rbac.local.k8s.roles.yaml' 
    - 'identity.local.k8s.deployment.yaml'
    - 'gso.local.k8s.deployment.yaml'
    - 'matchmaking.local.k8s.deployment.yaml'
