name: ci

on:
  push:
    branches:
      - master
      
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        api: [Identity.Server, MatchMaking.Api, GameServerOrchestrator]
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Debug folder contents
        run: ls -R
        
      - name: Build and test
        uses: docker/build-push-action@v6
        with:
          file: ./${{ matrix.api }}/Dockerfile
          target: publish
          load: true

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./${{ matrix.api }}
          file: ./${{ matrix.api }}/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          target: final
          tags: ${{ vars.DOCKER_USERNAME }}/${{ github.event.repository.name }}-${{ matrix.api }}:latest
